apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app9: nginx
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app2: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app3: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app2: nginx
  template:
    metadata:
      labels:
        app2: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

