apiVersion: v1
kind: Pod
metadata:
  name: mynginx-test2
  namespace: test
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: "900m"
        limits:
          memory: "4Gi"
          cpu: "2"


