apiVersion: v1
kind: Pod
metadata:
  name: mynginx-test2
  namespace: test
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        requests:
          memory: "100M"
          cpu: "100m"
        limits:
          memory: "100M"
          cpu: "100m"


