apiVersion: v1
kind: Pod
metadata:
  name: q1
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: q2
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: q3
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "200m"


