apiVersion: v1
kind: Pod
metadata:
  name: distribute-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: USERNAME_ENV
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: userdb      
    - name: PASSWORD_ENV
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: passworddb            

